general {
    fail_timeout = 1000
}

background {
    monitor =
    color = rgba(30, 35, 38, 1.0)
}

label {
    monitor =
    text = $TIME
    color = rgba(211, 198, 170, 1.0)
    font_size = 100
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 55
    halign = center
    valign = center
}

label {
    monitor =
    text = $DESC
    color = rgba(133, 146, 137, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, -27
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 240, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgba(167, 192, 128, 1.0)
    inner_color = rgba(39, 46, 51, 1.0)
    font_color = rgba(211, 198, 170, 1.0)

    fade_on_empty = false
    placeholder_text =
    hide_input = false

    check_color = rgba(167, 192, 128, 1.0)
    fail_color = rgba(230, 126, 128, 1.0)
    fail_text = <i>Ошибка ($ATTEMPTS)</i>

    rounding = 14
    position = 0, -110
    halign = center
    valign = center
}
